name: Continuos Integrations

on:
    push:
        branches: 
            ['master']

jobs:
    continuos-integrations:
        runs-on: ubuntu-latest

        steps:
            - name: Baixar repos
              uses: actions/checkout@v3
            - name: Versão Nodejs
              uses: actions/setup-node@v2
              with:
                node-version: 18.12.0
            - name: install Node e rodar build
              run: |
               yarn install
               yarn build


             